const seedRecipe = [
    {
        recipeName: "Deserti",
        instructions: ["Macro pugi ganteuss rufo griseus"],
        tags: ["Dipodomys deserti"],
        servings: "5",
        time: "41",
        ingredients: ["Libyca"],
    },
    {
        recipeName: "Schizachyrium rhizomatum",
        instructions: ["Thalasseus maximus"],
        tags: ["EBwsdHvh9m"],
        servings: "6",
        time: "25",
        ingredients: ["Ipochaeta", "Lavarum", "Gaudich"],
    },
    {
        recipeName: "Cervus Iguana",
        instructions: ["Laniarius ferrugineus"],
        tags: ["zK3EgbCDlG"],
        servings: "10",
        time: "60",
        ingredients: ["Duvauceli"],
    },
    {
        recipeName: "Tabernaemontana citrifolia",
        instructions: ["Otocyon megalotis"],
        tags: ["JI3SNZw"],
        servings: "4",
        time: "15",
        ingredients: ["Cokii"],
    },
    {
        recipeName: "Antilope cervicapra",
        instructions: ["Lysimachia ovoidea"],
        tags: ["Rubus occidentalis"],
        servings: "8",
        time: "45",
        ingredients: ["Thalasseus maximus"],
    },
    {
        recipeName: "Pennanti",
        instructions: ["Bejaria Mutis"],
        tags: ["Alcelaphus buselaphus"],
        servings: "6",
        time: "40",
        ingredients: ["Buccinator", "Ardea golieth"],
    },
    {
        recipeName: "Globicephala",
        instructions: ["Platalea leucordia", "radermachera moritzi satureja"],
        tags: ["melas"],
        servings: "20",
        time: "120",
        ingredients: ["Bates", "Eryngium", "Pinnatisectum-Jeps"],
    },
    {
        recipeName: "lozanii",
        instructions: ["Virginica diapensia lapponica", "Craterostigma", "plantagineum", "hochst", "eucephalus", "engelmannii"],
        tags: ["rUDqaJDipp9H"],
        servings: "2",
        time: "25",
        ingredients: ["Cygnus", "Bates", "Dipodomys"],
    },
    {
        recipeName: "Timmia",
        instructions: ["Austriaca villosissimus", "Echinochloa", "paludigena", "wiegand ex"],
        tags: ["6m6GWZ20"],
        servings: "10",
        time: "50",
        ingredients: ["Ninox", "Superciliaris", "Megalosporum", "Micromitrium"],
    },
    {
        recipeName: "Aeschynomene",
        instructions: ["Britton"],
        tags: ["Bradypus tridactylus"],
        servings: "14",
        time: "75",
        ingredients: ["Martes", "Ararauna"],
    },
];

module.exports = seedRecipe;
