export const UPDATE_RECIPES = "UPDATE_PRODUCTS";

export const ADD_TO_RECIPE = 'ADD_TO_RECIPE';
export const ADD_TO_GROCERY_LIST = 'ADD_TO_GROCERY_LIST';
export const REMOVE_FROM_RECIPE = 'REMOVE_FROM_RECIPE';



